-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.user_full_name(user_row users)
-- RETURNS text AS $$
-- SELECT user_row.first_name || ' ' || user_row.last_name
-- $$
-- LANGUAGE sql
-- STABLE;
